// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drnidmoaodyxmfuswcdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRybmlkbW9hb2R5eG1mdXN3Y2RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjg5NjAsImV4cCI6MjA3MDYwNDk2MH0.shDiMx3Cv7xMyHS-VwooCBRGfuoG4gaHLyabfs0UnT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});